### ISSUE TITLE
Camera choice

### ISSUE THREAD

**Issue by rwb27** [openUC2/UC2_openSIM#4]
I realise that I have focused most of my efforts on the SIM module and not the rest of the microscope!  I think mostly it's just mirrors and UC2 cubes, but I realise there is a camera in there.  You specify "Allied Vision Alvium" but no model number.  What did you use? Which features were important?  I guess they are probably all fairly reasonable, but there's a big range of sensor sizes (and thus prices) so it would be good to know!  Did you use a USB version or MIPI with a Jetson Nano?

**Comment by beniroquai** [comment]
Hey, by the time we were starting the project we wanted to do everything on the Jetson Nano. Now after we gained lots of experience and talked to people we would rather go for another sensor I guess. We used the allied vision 158 Alvium chip (e.g. [Edmund](https://www.edmundoptics.de/p/allied-vision-alvium-1800-u-158m-129-158mp-c-mount-usb-31-monochrome-camera/44757/). It's cheap and works ok with the Jetson. Also I tried adapting the Openflexure to talk to this camera. We do STORM and SIM with it, but it does not talk to MicroManager.

We tried the MIPI and the USB version. MIPI uses the V4L2 interface that cannot provide the 12 bit stream for some reason. The USB version offers full VIMBA support which is actually very nice (Python, C bindings, etc.)

So the Huser Lab makes use of the Sony IMX174 in dSTORM and SIM. It has large pixels (5.6µm vs 3.4µm I guess) and higher QE. Costs a bit more, but I recently ordered a chip from Daheng that costs 500€. It has a python interface + jetson drivers too (see SQUID paper from the Prakash Lab; [European distributor](https://www.get-cameras.com/USB-Camera-3.0-2.3MP-Monochrome-Sony-IMX174-MER2-230-168U3M). 
IDS and Basler has the sensor, costs a bit more, but has much better drivers it says. 

The IDS and Daheng IMX 174 should arrive in the next weeks. I can tell you more then! :) 

Alternatively: SIM with the Raspberry PI would be fun. Synthetic dyes + high laser power could totally make that happen. Sampling is then of course a fun thing ;-)
