### ISSUE TITLE
Parts out of production; replacement suggestions

### ISSUE THREAD

**Issue by b2jia** [openUC2/UC2_openSIM#8]
Thanks again for providing this amazing public resource!

A couple of questions:

- Tube-lens : the f=180 mm lens from PGI-Versand no longer appears to be available. Is there a part from ThorLabs the authors might be able to recommend? Is there enough tolerance to accomodate an f = 200 mm lens such as [AC254-200-A-ML](https://www.thorlabs.de/thorproduct.cfm?partnumber=AC254-200-A-ML)
- Dichroics : it seems the ComarOptics 740 IY 125 40x25mm is also no longer available. Is the [DMLP638R] (https://www.thorlabs.de/thorproduct.cfm?partnumber=DMLP638R) a suitable replacement? Dimensions are a bit off (36x25mm) and the cut-on wavelength is close but not exact.

**Comment by ranranking** [comment]
Hey,
thanks for reaching us!

- for the tube lens, sure zou can exchange it with thorlabs 200mm lens. As the imaging part is separate sitting on the ground floor, it should be fine to adjust it into infinity. Just be aware that the cube has 50mm size, so it could be the right position of the lens sits somewhere between two cubes. If it is like that, you might need to have a short extend thorlabs 1inch tube to satisify it.
- the 638R seems fine to me, the only problem to me is cuton wavelength is quite near to the emitting laser. It might need a bit higher output so you can get enough on your sample. Otherweise this dichroic might fits the wavelength better, but also a bit expensive. https://www.thorlabs.de/thorproduct.cfm?partnumber=DMLP650R  But both should be working.

If you get any new problem, just write us back, i will try to help you out.
Best Regards

**Comment by b2jia** [comment]
Thanks for your response! 

- Just to confirm, by extension tube, it is just a simple [stackable lens tube ie. (SM1L10)] (https://www.thorlabs.com/thorproduct.cfm?partnumber=CM1L10), this looks sufficient?
- In case others are also reading this thread, Chroma has some reasonably priced dichroics: https://www.chroma.com/products/parts/t647lpxr

**Comment by ranranking** [comment]
I was expecting some tubes like that https://www.thorlabs.com/thorproduct.cfm?partnumber=SM1L03
if you want to use c mount ones, i think you need to screw it onto your camera. I dont think you can screw it into thorlabs cages
